//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the turtlebot_example package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __turtlebot_example__LAB2CONFIG_H__
#define __turtlebot_example__LAB2CONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace turtlebot_example
{
  class lab2ConfigStatics;
  
  class lab2Config
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(lab2Config &config, const lab2Config &max, const lab2Config &min) const = 0;
      virtual void calcLevel(uint32_t &level, const lab2Config &config1, const lab2Config &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, lab2Config &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const lab2Config &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, lab2Config &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const lab2Config &config) const = 0;
      virtual void getValue(const lab2Config &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T lab2Config::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (lab2Config::* field);

      virtual void clamp(lab2Config &config, const lab2Config &max, const lab2Config &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const lab2Config &config1, const lab2Config &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, lab2Config &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const lab2Config &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, lab2Config &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const lab2Config &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const lab2Config &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, lab2Config &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, lab2Config &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<lab2Config::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(lab2Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("nParticles"==(*_i)->name){nParticles = boost::any_cast<int>(val);}
        if("posPriorRange"==(*_i)->name){posPriorRange = boost::any_cast<double>(val);}
        if("thetaPriorRange"==(*_i)->name){thetaPriorRange = boost::any_cast<double>(val);}
        if("maxMeasRange"==(*_i)->name){maxMeasRange = boost::any_cast<double>(val);}
        if("maxMeasTheta"==(*_i)->name){maxMeasTheta = boost::any_cast<double>(val);}
        if("mapGridSize"==(*_i)->name){mapGridSize = boost::any_cast<double>(val);}
        if("mapSize"==(*_i)->name){mapSize = boost::any_cast<double>(val);}
        if("emptySpaceProbModifier"==(*_i)->name){emptySpaceProbModifier = boost::any_cast<double>(val);}
        if("notEmptySpaceProbModifier"==(*_i)->name){notEmptySpaceProbModifier = boost::any_cast<double>(val);}
        if("scanSkipCnt"==(*_i)->name){scanSkipCnt = boost::any_cast<int>(val);}
        if("mapBeta"==(*_i)->name){mapBeta = boost::any_cast<int>(val);}
      }
    }

    int nParticles;
double posPriorRange;
double thetaPriorRange;
double maxMeasRange;
double maxMeasTheta;
double mapGridSize;
double mapSize;
double emptySpaceProbModifier;
double notEmptySpaceProbModifier;
int scanSkipCnt;
int mapBeta;

    bool state;
    std::string name;

    
}groups;



//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int nParticles;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double posPriorRange;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double thetaPriorRange;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double maxMeasRange;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double maxMeasTheta;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double mapGridSize;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double mapSize;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double emptySpaceProbModifier;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double notEmptySpaceProbModifier;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int scanSkipCnt;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int mapBeta;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("lab2Config::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const lab2Config &__max__ = __getMax__();
      const lab2Config &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const lab2Config &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const lab2Config &__getDefault__();
    static const lab2Config &__getMax__();
    static const lab2Config &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const lab2ConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void lab2Config::ParamDescription<std::string>::clamp(lab2Config &config, const lab2Config &max, const lab2Config &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class lab2ConfigStatics
  {
    friend class lab2Config;
    
    lab2ConfigStatics()
    {
lab2Config::GroupDescription<lab2Config::DEFAULT, lab2Config> Default("Default", "", 0, 0, true, &lab2Config::groups);
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.nParticles = 1;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.nParticles = 10000;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.nParticles = 100;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<int>("nParticles", "int", 0, "nParticles.", "", &lab2Config::nParticles)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<int>("nParticles", "int", 0, "nParticles.", "", &lab2Config::nParticles)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.posPriorRange = 0.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.posPriorRange = 10.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.posPriorRange = 1.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("posPriorRange", "double", 0, "posPriorRange.", "", &lab2Config::posPriorRange)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("posPriorRange", "double", 0, "posPriorRange.", "", &lab2Config::posPriorRange)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.thetaPriorRange = 0.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.thetaPriorRange = 3.14159265359;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.thetaPriorRange = 1.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("thetaPriorRange", "double", 0, "thetaPriorRange.", "", &lab2Config::thetaPriorRange)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("thetaPriorRange", "double", 0, "thetaPriorRange.", "", &lab2Config::thetaPriorRange)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.maxMeasRange = 0.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.maxMeasRange = 50.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.maxMeasRange = 9.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("maxMeasRange", "double", 0, "Maximum range of measurement to accept for mapping.", "", &lab2Config::maxMeasRange)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("maxMeasRange", "double", 0, "Maximum range of measurement to accept for mapping.", "", &lab2Config::maxMeasRange)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.maxMeasTheta = 0.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.maxMeasTheta = 1.57079632679;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.maxMeasTheta = 0.785398163397;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("maxMeasTheta", "double", 0, "Maximum angle of measurement to accept for mapping.", "", &lab2Config::maxMeasTheta)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("maxMeasTheta", "double", 0, "Maximum angle of measurement to accept for mapping.", "", &lab2Config::maxMeasTheta)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.mapGridSize = 1e-06;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.mapGridSize = 10.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.mapGridSize = 0.01;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("mapGridSize", "double", 0, "The size of a square of a map grid in meters.", "", &lab2Config::mapGridSize)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("mapGridSize", "double", 0, "The size of a square of a map grid in meters.", "", &lab2Config::mapGridSize)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.mapSize = 1.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.mapSize = 50.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.mapSize = 20.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("mapSize", "double", 0, "The size of the map in meters.", "", &lab2Config::mapSize)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("mapSize", "double", 0, "The size of the map in meters.", "", &lab2Config::mapSize)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.emptySpaceProbModifier = 0.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.emptySpaceProbModifier = 0.5;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.emptySpaceProbModifier = 0.4;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("emptySpaceProbModifier", "double", 0, "The probability that a space is occupied given that there was no measured object there.", "", &lab2Config::emptySpaceProbModifier)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("emptySpaceProbModifier", "double", 0, "The probability that a space is occupied given that there was no measured object there.", "", &lab2Config::emptySpaceProbModifier)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.notEmptySpaceProbModifier = 0.5;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.notEmptySpaceProbModifier = 1.0;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.notEmptySpaceProbModifier = 0.6;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("notEmptySpaceProbModifier", "double", 0, "The probability that a space is occupied given that there was a measured object there.", "", &lab2Config::notEmptySpaceProbModifier)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<double>("notEmptySpaceProbModifier", "double", 0, "The probability that a space is occupied given that there was a measured object there.", "", &lab2Config::notEmptySpaceProbModifier)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.scanSkipCnt = 1;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.scanSkipCnt = 10;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.scanSkipCnt = 1;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<int>("scanSkipCnt", "int", 0, "How many scans to skip for mapping.", "", &lab2Config::scanSkipCnt)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<int>("scanSkipCnt", "int", 0, "How many scans to skip for mapping.", "", &lab2Config::scanSkipCnt)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.mapBeta = 1;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.mapBeta = 100;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.mapBeta = 5;
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<int>("mapBeta", "int", 0, "How many grid cells to consider as part of the object in a trace.", "", &lab2Config::mapBeta)));
//#line 273 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(lab2Config::AbstractParamDescriptionConstPtr(new lab2Config::ParamDescription<int>("mapBeta", "int", 0, "How many grid cells to consider as part of the object in a trace.", "", &lab2Config::mapBeta)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(lab2Config::AbstractGroupDescriptionConstPtr(new lab2Config::GroupDescription<lab2Config::DEFAULT, lab2Config>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<lab2Config::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<lab2Config::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<lab2Config::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    lab2Config __max__;
    lab2Config __min__;
    lab2Config __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const lab2ConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static lab2ConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &lab2Config::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const lab2Config &lab2Config::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const lab2Config &lab2Config::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const lab2Config &lab2Config::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<lab2Config::AbstractParamDescriptionConstPtr> &lab2Config::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<lab2Config::AbstractGroupDescriptionConstPtr> &lab2Config::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const lab2ConfigStatics *lab2Config::__get_statics__()
  {
    const static lab2ConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = lab2ConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __LAB2RECONFIGURATOR_H__
